language: ruby
sudo: false
rvm: 2.2.0
script: bundle exec rake deploy
env:
  global:
    secure: nHWOkMZWlqfTG1WEfPBIWW/iUg0mIqKBBW2TXPxh3pmqD7S73gurcZbqkJPK5OOJ/X9QJnqT7A9cxE00B7WLewck886jTHlKGIr3o2GTQhYMp15ZjCtNbWVt3pLP0mkc9GKpTHxlTgl8/6Pm51hkmA5i2146XMh778r/h2sAG/tNKTpI0+N8K7VmDLHAi7j4+GyJnNac5ogswmB6aR0ntyIbpMZmlShJoeqNFykFFX2EpITbSY5k6cYCBXvWlCWsIYo0HmN/Nt1hNaSwFHdFZ51hGHvSHNEwYj3naXjEvBd2Bcs9JrldxzHFbDiBEbeRjIOAtcBMyVVIgmiGQ5q7r/kbjPUmZIlwOIyyBCPD02QblEGehihwBhXiMnSqKcc9X6m6JW7yd1qKXwUfkwucOjjC6t2dYkgWUxzX6q61lMOEpqmjYBWYmg2r7k40q0r3VcY1UK6De3M69w0sFm2ykwNlPd/YpMnzl5R3pdOqUB7VXq86OsQoTgfA8n/E1EfAz37cGO6kf+VWYyZsScDoQ0SjIqAj9Lx6ee/eJhJO9n/t0OxaOixIjlICgbLF4A9PjoWI3G0rdHnA4ke+VtpyK8HqPllYqmYFi997m+gK6iZwbjxfiAU+3glD0uf5X8yZgQCtSb+Zxsco8A2xuZ9A3tAAGOULNlyLM4M0MslALGc=
